fix(husky_ws): Fix package not found issue by removing the redundant `nmea_navsat_driver` used by J100
Error message:

    E: Failed to fetch https://packages.clearpathrobotics.com/stable/ubuntu/pool/main/r/ros-humble-nmea-navsat-driver/ros-humble-nmea-navsat-driver_2.0.2-1jammy.20240722.193159_amd64.deb  404  Not Found [IP: 24.114.195.222 443]
    E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
    ERROR: the following rosdeps failed to install
      apt: command [sudo -H apt-get install -y ros-humble-nmea-navsat-driver] failed