fix(template_ws): Correctly fix Isaac Sim volume mount permission issues
Note that the previous commit 8bfa852 isn't a complete fix, and will cause issue when running:

    $ pip install torch
    OSError: [Errno 13] Permission denied: '/home/user/.local/share/man'